queryParameters:
  query:
    description: |
      The fields <<fields>> can be used to filter data. By example
      to search by the field '<<field>>' equals to '<<value>>' we would need to
      build our query as follow "query=<<field>>:<<value>>". Multiple fields
      search should be delimited by a comma.
    type: string
    required: false
