queryParameters:
  sortBy:
    description: |
      The fields <<fields>> can be used to sort the response. By example
      to sort the response by the field '<<field>>' ascendently or descendently we
      would just need to add the sign plus '+' or minus '-' in front of it.
      To sort by more than one field, just separete each field by a comma.
      Usage: "sortBy=+<<field>>".
    type: string
    required: false
