-- MySQL Script generated by MySQL Workbench
-- Fri Nov  2 07:26:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema accounts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accounts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` VARCHAR(40) NOT NULL,
  `subdomain` VARCHAR(63) NOT NULL,
  `configurations` JSON NULL,
  `verified` TINYINT NOT NULL DEFAULT 0,
  `status` ENUM('ACTIVE', 'BLOCKED') NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `subdomain_UNIQUE` (`subdomain` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account_candidates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account_candidates` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `candidate_id` VARCHAR(40) NOT NULL,
  `account_id` BIGINT NOT NULL,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone_country_code` VARCHAR(10) NULL,
  `phone` VARCHAR(20) NULL,
  `candidate_for` VARCHAR(120) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `candidate_id_UNIQUE` (`candidate_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_candidates_accounts_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_candidates_accounts`
    FOREIGN KEY (`account_id`)
    REFERENCES `accounts` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
