-- MySQL Script generated by MySQL Workbench
-- Tue Nov 27 16:43:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema app365
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(40) NOT NULL,
  `auth_user_id` BIGINT NULL,
  `first_name` VARCHAR(60) NULL,
  `last_name` VARCHAR(60) NULL,
  `nickname` VARCHAR(40) NULL,
  `id_card` VARCHAR(40) NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone_country_code` VARCHAR(10) NULL,
  `phone` VARCHAR(20) NULL,
  `phone_verified` TINYINT NOT NULL DEFAULT 0,
  `phone_verification_code` VARCHAR(40) NULL,
  `emitted_phone_code_count` TINYINT NOT NULL DEFAULT 0,
  `last_phone_verification_code_sent_at` DATETIME NULL,
  `email_verified` TINYINT NOT NULL DEFAULT 0,
  `email_verification_code` VARCHAR(40) NULL,
  `email_verified_at` DATETIME NULL,
  `birth_date` DATE NULL,
  `profile_picture` VARCHAR(255) NULL,
  `channel` VARCHAR(40) NOT NULL,
  `social_identifier` VARCHAR(120) NULL,
  `meta` JSON NULL,
  `settings` JSON NULL,
  `time_zone_offset` INT NOT NULL,
  `time_zone` VARCHAR(255) NOT NULL,
  `language` VARCHAR(40) NULL,
  `verified` TINYINT NOT NULL DEFAULT 0,
  `active` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `auth_user_id_UNIQUE` (`auth_user_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devices` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `device_id` VARCHAR(40) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `platform` VARCHAR(40) NOT NULL,
  `firebase_token` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `device_id_UNIQUE` (`device_id` ASC) VISIBLE,
  INDEX `fk_devices_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_devices_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medals` (
  `id` INT NOT NULL,
  `medal_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `description` VARCHAR(255) NULL,
  `instructions` TEXT NULL,
  `benefits` TEXT NULL,
  `points` INT NOT NULL DEFAULT 0,
  `image` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `medal_id_UNIQUE` (`medal_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `image_UNIQUE` (`image` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awards` (
  `user_id` BIGINT NOT NULL,
  `medal_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`medal_id`, `user_id`),
  INDEX `fk_users_medals_medals1_idx` (`medal_id` ASC) VISIBLE,
  INDEX `fk_users_medals_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_medals_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_medals_medals1`
    FOREIGN KEY (`medal_id`)
    REFERENCES `medals` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_id` VARCHAR(40) NOT NULL,
  `iso2` VARCHAR(2) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `country_id_UNIQUE` (`country_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `states` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `state_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `country_id` INT NOT NULL,
  `user_defined` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `province_id_UNIQUE` (`state_id` ASC) VISIBLE,
  INDEX `fk_province_country1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_province_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `countries` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `municipalities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `municipalities` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `municipality_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `state_id` BIGINT NULL,
  `user_defined` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `province_id_UNIQUE` (`municipality_id` ASC) VISIBLE,
  INDEX `fk_municipality_province1_idx` (`state_id` ASC) VISIBLE,
  CONSTRAINT `fk_municipality_province1`
    FOREIGN KEY (`state_id`)
    REFERENCES `states` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cities` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `city_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `municipality_id` BIGINT NULL,
  `user_defined` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `province_id_UNIQUE` (`city_id` ASC) VISIBLE,
  INDEX `fk_city_municipality1_idx` (`municipality_id` ASC) VISIBLE,
  CONSTRAINT `fk_city_municipality1`
    FOREIGN KEY (`municipality_id`)
    REFERENCES `municipalities` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sectors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sectors` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `sector_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `city_id` BIGINT NULL,
  `user_defined` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `province_id_UNIQUE` (`sector_id` ASC) VISIBLE,
  INDEX `fk_sector_city1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_sector_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `cities` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addresses` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `street` VARCHAR(255) NULL,
  `home` VARCHAR(40) NULL,
  `apartment` VARCHAR(40) NULL,
  `reference` VARCHAR(255) NULL,
  `additional_sector` VARCHAR(255) NULL,
  `zip_code` VARCHAR(20) NULL,
  `country_id` INT NOT NULL,
  `state_id` BIGINT NULL,
  `municipality_id` BIGINT NULL,
  `city_id` BIGINT NULL,
  `sector_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_country1_idx` (`country_id` ASC) VISIBLE,
  INDEX `fk_address_province1_idx` (`state_id` ASC) VISIBLE,
  INDEX `fk_address_municipality1_idx` (`municipality_id` ASC) VISIBLE,
  INDEX `fk_address_city1_idx` (`city_id` ASC) VISIBLE,
  INDEX `fk_address_sector1_idx` (`sector_id` ASC) VISIBLE,
  INDEX `fk_address_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `countries` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_address_province1`
    FOREIGN KEY (`state_id`)
    REFERENCES `states` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_address_municipality1`
    FOREIGN KEY (`municipality_id`)
    REFERENCES `municipalities` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `cities` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_address_sector1`
    FOREIGN KEY (`sector_id`)
    REFERENCES `sectors` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_address_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notifications` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `notification_id` VARCHAR(40) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `content` VARCHAR(255) NULL,
  `type` VARCHAR(120) NOT NULL,
  `target` VARCHAR(255) NULL,
  `extras` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `notification_id_UNIQUE` (`notification_id` ASC) VISIBLE,
  INDEX `fk_notifications_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_notifications_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `news_id` VARCHAR(40) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `content` TEXT NULL,
  `cover_picture` VARCHAR(255) NULL,
  `is_flagged` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `event_id_UNIQUE` (`news_id` ASC) VISIBLE,
  INDEX `fk_news_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_news_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news_summary` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `news_id` BIGINT NOT NULL,
  `share_count` INT NOT NULL DEFAULT 0,
  `comment_count` INT NOT NULL DEFAULT 0,
  `like_count` INT NOT NULL DEFAULT 0,
  `last_share_at` DATETIME NULL,
  `last_comment_at` DATETIME NULL,
  `last_like_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_news_summary_news1_idx` (`news_id` ASC) VISIBLE,
  CONSTRAINT `fk_news_summary_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `news` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news_comments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `comment_id` VARCHAR(40) NOT NULL,
  `news_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC) VISIBLE,
  INDEX `fk_comments_news1_idx` (`news_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comments_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `news` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news_likes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `news_id` BIGINT NOT NULL,
  `liked` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_likes_news1_idx` (`news_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_news_like1_idx` (`user_id` ASC, `news_id` ASC) VISIBLE,
  CONSTRAINT `fk_likes_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_likes_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `news` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news_shares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news_shares` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `news_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_shares_news1_idx` (`news_id` ASC) VISIBLE,
  CONSTRAINT `fk_likes_users10`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shares_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `news` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_id` VARCHAR(40) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `content` TEXT NULL,
  `cover_picture` VARCHAR(255) NULL,
  `is_flagged` TINYINT NOT NULL DEFAULT 0,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `event_id_UNIQUE` (`event_id` ASC) VISIBLE,
  INDEX `fk_events_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event_joins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_joins` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `join_id` VARCHAR(40) NOT NULL,
  `event_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `joined` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_joins_events1_idx` (`event_id` ASC) VISIBLE,
  INDEX `fk_joins_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `join_id_UNIQUE` (`join_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_event_user1_idx` (`event_id` ASC, `user_id` ASC) VISIBLE,
  CONSTRAINT `fk_joins_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `events` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_joins_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `calendars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calendars` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `event_id` BIGINT NOT NULL,
  `calendar_id` VARCHAR(40) NOT NULL,
  `platform` VARCHAR(40) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_calendars_events1_idx` (`event_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_event_user1_idx` (`event_id` ASC, `user_id` ASC) VISIBLE,
  CONSTRAINT `fk_likes_users100`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_calendars_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `events` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `location` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `location_id` VARCHAR(40) NOT NULL,
  `event_id` BIGINT NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `location_id_UNIQUE` (`location_id` ASC) VISIBLE,
  INDEX `fk_location_events1_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_location_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `events` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `video_id` VARCHAR(40) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `content` TEXT NULL,
  `thumbnail` VARCHAR(255) NULL,
  `url` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `event_id_UNIQUE` (`video_id` ASC) VISIBLE,
  INDEX `fk_videos_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_videos_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `video_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_summary` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `video_id` BIGINT NOT NULL,
  `share_count` INT NOT NULL DEFAULT 0,
  `comment_count` INT NOT NULL DEFAULT 0,
  `like_count` INT NOT NULL DEFAULT 0,
  `last_share_at` DATETIME NULL,
  `last_comment_at` DATETIME NULL,
  `last_like_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_video_summary_videos1_idx` (`video_id` ASC) VISIBLE,
  CONSTRAINT `fk_video_summary_videos1`
    FOREIGN KEY (`video_id`)
    REFERENCES `videos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_summary` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_id` BIGINT NOT NULL,
  `join_count` INT NOT NULL DEFAULT 0,
  `share_count` INT NOT NULL DEFAULT 0,
  `comment_count` INT NOT NULL DEFAULT 0,
  `like_count` INT NOT NULL DEFAULT 0,
  `last_joined_at` DATETIME NULL,
  `last_share_at` DATETIME NULL,
  `last_comment_at` DATETIME NULL,
  `last_like_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_summary_events1_idx` (`event_id` ASC) VISIBLE,
  UNIQUE INDEX `event_id_UNIQUE` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_summary_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `events` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_comments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `comment_id` VARCHAR(40) NOT NULL,
  `event_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC) VISIBLE,
  INDEX `fk_event_comments_events1_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users10`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_event_comments_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `events` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_likes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `liked` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_event_likes_events1_idx` (`event_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_event_user1_idx` (`user_id` ASC, `event_id` ASC) VISIBLE,
  CONSTRAINT `fk_likes_users11`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_event_likes_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `events` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event_shares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_shares` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_event_shares_events1_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_likes_users101`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_event_shares_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `events` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `video_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_likes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `video_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `liked` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_video_likes_videos1_idx` (`video_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_video_user1_idx` (`user_id` ASC, `video_id` ASC) VISIBLE,
  CONSTRAINT `fk_likes_users12`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_video_likes_videos1`
    FOREIGN KEY (`video_id`)
    REFERENCES `videos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `video_shares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_shares` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `video_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_video_shares_videos1_idx` (`video_id` ASC) VISIBLE,
  CONSTRAINT `fk_likes_users102`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_video_shares_videos1`
    FOREIGN KEY (`video_id`)
    REFERENCES `videos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `video_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_comments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `comment_id` VARCHAR(40) NOT NULL,
  `video_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC) VISIBLE,
  INDEX `fk_video_comments_videos1_idx` (`video_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users11`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_video_comments_videos1`
    FOREIGN KEY (`video_id`)
    REFERENCES `videos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `volunteers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `volunteers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_volunteers_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_volunteers_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `task_id_UNIQUE` (`task_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schedules` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `schedule_id` VARCHAR(40) NOT NULL,
  `volunteer_id` BIGINT NOT NULL,
  `task_id` INT NOT NULL,
  `note` VARCHAR(255) NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `repeat_until` DATE NULL,
  `repeat_days` JSON NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schedules_volunteers1_idx` (`volunteer_id` ASC) VISIBLE,
  UNIQUE INDEX `schedule_id_UNIQUE` (`schedule_id` ASC) VISIBLE,
  INDEX `fk_schedules_tasks1_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedules_volunteers1`
    FOREIGN KEY (`volunteer_id`)
    REFERENCES `volunteers` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_schedules_tasks1`
    FOREIGN KEY (`task_id`)
    REFERENCES `tasks` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `slides` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `slide_id` VARCHAR(40) NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slide_id_UNIQUE` (`slide_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `candidates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `candidates` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `candidate_id` VARCHAR(40) NOT NULL,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `id_card` VARCHAR(40) NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone_country_code` VARCHAR(10) NULL,
  `phone` VARCHAR(20) NULL,
  `birth_date` DATE NULL,
  `biography_description` TEXT NULL,
  `profile_picture` VARCHAR(255) NULL,
  `social_identifier` VARCHAR(120) NULL,
  `utc_offset` TIME NULL,
  `time_zone` VARCHAR(255) NULL,
  `language` VARCHAR(40) NULL,
  `candidate_for` VARCHAR(120) NULL,
  `social_tokens` JSON NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`candidate_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `candidate_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `candidate_likes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `candidate_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `liked` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_candidate_likes_candidates1_idx` (`candidate_id` ASC) VISIBLE,
  INDEX `fk_candidate_likes_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_candidate_likes1_idx` (`user_id` ASC, `candidate_id` ASC) VISIBLE,
  CONSTRAINT `fk_candidate_likes_candidates1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `candidates` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidate_likes_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `candidate_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `candidate_comments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `comment_id` VARCHAR(40) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `candidate_id` BIGINT NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC) VISIBLE,
  INDEX `fk_candidate_comments_candidates1_idx` (`candidate_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users110`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidate_comments_candidates1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `candidates` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `candidate_shares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `candidate_shares` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `candidate_id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_candidate_shares_candidates1_idx` (`candidate_id` ASC) VISIBLE,
  CONSTRAINT `fk_likes_users103`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidate_shares_candidates1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `candidates` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `post_id` VARCHAR(40) NOT NULL,
  `candidate_id` BIGINT NOT NULL,
  `content` TEXT NOT NULL,
  `channel` ENUM('FACEBOOK', 'TWITTER') NOT NULL,
  `external_post_id` VARCHAR(120) NULL,
  `external_created_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `comment_id_UNIQUE` (`post_id` ASC) VISIBLE,
  INDEX `fk_posts_candidates1_idx` (`candidate_id` ASC) VISIBLE,
  UNIQUE INDEX `external_post_id_UNIQUE` (`external_post_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_candidates1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `candidates` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `post_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `post_comments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `comment_id` VARCHAR(40) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `post_id` BIGINT NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC) VISIBLE,
  INDEX `fk_post_comments_posts1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users1100`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_comments_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `posts` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `candidate_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `candidate_users` (
  `candidate_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`candidate_id`, `user_id`),
  INDEX `fk_candidates_users_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_candidates_users_candidates1_idx` (`candidate_id` ASC) VISIBLE,
  CONSTRAINT `fk_candidates_users_candidates1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `candidates` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidates_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `party` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `party_id` VARCHAR(40) NOT NULL,
  `candidate_id` BIGINT NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `name_abbr` VARCHAR(60) NULL,
  `banner_picture` VARCHAR(255) NULL,
  `slogan` VARCHAR(120) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `party_id_UNIQUE` (`party_id` ASC) VISIBLE,
  INDEX `fk_party_candidates1_idx` (`candidate_id` ASC) VISIBLE,
  CONSTRAINT `fk_party_candidates1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `candidates` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `candidate_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `candidate_summary` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `candidate_id` BIGINT NOT NULL,
  `donation_count` INT NOT NULL DEFAULT 0,
  `offer_count` INT NOT NULL DEFAULT 0,
  `like_count` INT NOT NULL DEFAULT 0,
  `share_count` INT NOT NULL DEFAULT 0,
  `comment_count` INT NOT NULL DEFAULT 0,
  `post_count` INT NOT NULL DEFAULT 0,
  `post_comment_count` INT NOT NULL DEFAULT 0,
  `last_donation_at` DATETIME NULL,
  `last_offer_at` DATETIME NULL,
  `last_like_at` DATETIME NULL,
  `last_share_at` DATETIME NULL,
  `last_comment_at` DATETIME NULL,
  `last_post_at` DATETIME NULL,
  `last_post_comment_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_candidate_summary_candidates1_idx` (`candidate_id` ASC) VISIBLE,
  CONSTRAINT `fk_candidate_summary_candidates1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `candidates` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `candidate_donations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `candidate_donations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `donation_id` VARCHAR(40) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `candidate_id` BIGINT NOT NULL,
  `amount` DECIMAL(13,4) NOT NULL,
  `currency` VARCHAR(40) NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `comment_id_UNIQUE` (`donation_id` ASC) VISIBLE,
  INDEX `fk_candidate_comments_candidates1_idx` (`candidate_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users1101`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidate_comments_candidates10`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `candidates` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `candidate_offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `candidate_offers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `offer_id` VARCHAR(40) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `candidate_id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `comment_id_UNIQUE` (`offer_id` ASC) VISIBLE,
  INDEX `fk_candidate_comments_candidates1_idx` (`candidate_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users11010`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidate_comments_candidates100`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `candidates` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citizens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citizens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `citizen_id` VARCHAR(40) NOT NULL,
  `id_card` VARCHAR(40) NOT NULL,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `citizen_id_UNIQUE` (`citizen_id` ASC) VISIBLE,
  UNIQUE INDEX `id_card_UNIQUE` (`id_card` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team_members` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `member_id` VARCHAR(40) NOT NULL,
  `citizen_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `parent_id` BIGINT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_members_citizens1_idx` (`citizen_id` ASC) VISIBLE,
  INDEX `fk_members_users2_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `member_id_UNIQUE` (`member_id` ASC) VISIBLE,
  INDEX `fk_team_members_team_members1_idx` (`parent_id` ASC) VISIBLE,
  UNIQUE INDEX `citizen_id_UNIQUE` (`citizen_id` ASC) VISIBLE,
  CONSTRAINT `fk_members_citizens1`
    FOREIGN KEY (`citizen_id`)
    REFERENCES `citizens` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_members_users2`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_team_members_team_members1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `team_members` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `action_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `action_types` (
  `name` VARCHAR(40) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medal_rules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medal_rules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medal_rule_id` VARCHAR(40) NOT NULL,
  `medal_id` INT NOT NULL,
  `action_type_name` VARCHAR(40) NOT NULL,
  `total` DOUBLE NOT NULL,
  UNIQUE INDEX `medal_point_id_UNIQUE` (`medal_rule_id` ASC) VISIBLE,
  INDEX `fk_medal_rules_medals1_idx` (`medal_id` ASC) VISIBLE,
  INDEX `fk_medal_rules_user_action_types1_idx` (`action_type_name` ASC) VISIBLE,
  UNIQUE INDEX `medal_id_action_type_name_UNIQUE` (`medal_id` ASC, `action_type_name` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_medal_rules_medals1`
    FOREIGN KEY (`medal_id`)
    REFERENCES `medals` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_medal_rules_user_action_types1`
    FOREIGN KEY (`action_type_name`)
    REFERENCES `action_types` (`name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_rules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_rules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `point_rule_id` VARCHAR(40) NOT NULL,
  `action_type_name` VARCHAR(40) NOT NULL,
  `frequency` DOUBLE NULL,
  `points` INT NOT NULL,
  UNIQUE INDEX `medal_point_id_UNIQUE` (`point_rule_id` ASC) VISIBLE,
  INDEX `fk_point_rules_user_action_types1_idx` (`action_type_name` ASC) VISIBLE,
  UNIQUE INDEX `action_type_name_UNIQUE` (`action_type_name` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_point_rules_user_action_types1`
    FOREIGN KEY (`action_type_name`)
    REFERENCES `action_types` (`name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_points` (
  `user_id` BIGINT NOT NULL,
  `action_type_name` VARCHAR(40) NOT NULL,
  `points` VARCHAR(40) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`user_id`, `action_type_name`),
  INDEX `fk_users_user_action_types_user_action_types1_idx` (`action_type_name` ASC) VISIBLE,
  INDEX `fk_users_user_action_types_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_user_action_types_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_user_action_types_user_action_types1`
    FOREIGN KEY (`action_type_name`)
    REFERENCES `action_types` (`name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vote_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vote_center` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `vote_center_id` VARCHAR(40) NOT NULL,
  `code` VARCHAR(40) NULL,
  `name` VARCHAR(255) NOT NULL,
  `picture` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `location_latitude` DOUBLE NULL,
  `location_longitude` DOUBLE NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `vote_center_id_UNIQUE` (`vote_center_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citizen_addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citizen_addresses` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `citizen_id` BIGINT NOT NULL,
  `street` VARCHAR(255) NULL,
  `home` VARCHAR(40) NULL,
  `apartment` VARCHAR(40) NULL,
  `reference` VARCHAR(255) NULL,
  `zip_code` VARCHAR(20) NULL,
  `country_id` INT NOT NULL,
  `state_id` BIGINT NULL,
  `municipality_id` BIGINT NULL,
  `city_id` BIGINT NULL,
  `sector_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_country1_idx` (`country_id` ASC) VISIBLE,
  INDEX `fk_address_province1_idx` (`state_id` ASC) VISIBLE,
  INDEX `fk_address_municipality1_idx` (`municipality_id` ASC) VISIBLE,
  INDEX `fk_address_city1_idx` (`city_id` ASC) VISIBLE,
  INDEX `fk_address_sector1_idx` (`sector_id` ASC) VISIBLE,
  INDEX `fk_citizen_addresses_citizens1_idx` (`citizen_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_country10`
    FOREIGN KEY (`country_id`)
    REFERENCES `countries` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_address_province10`
    FOREIGN KEY (`state_id`)
    REFERENCES `states` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_address_municipality10`
    FOREIGN KEY (`municipality_id`)
    REFERENCES `municipalities` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_address_city10`
    FOREIGN KEY (`city_id`)
    REFERENCES `cities` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_address_sector10`
    FOREIGN KEY (`sector_id`)
    REFERENCES `sectors` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_citizen_addresses_citizens1`
    FOREIGN KEY (`citizen_id`)
    REFERENCES `citizens` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elections` (
  `id` INT NOT NULL,
  `election_id` VARCHAR(40) NOT NULL,
  `election_type` VARCHAR(120) NOT NULL,
  `election_date` DATE NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `election_id_UNIQUE` (`election_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Placeholder table for view `v_team_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `v_team_members` (`id` INT, `member_id` INT, `user_id` INT, `parent_id` INT, `member_since` INT, `citizen_id` INT, `citizen_uuid` INT, `id_card` INT, `first_name` INT, `last_name` INT, `member_count` INT, `level_count` INT);

-- -----------------------------------------------------
-- function get_team_level_count
-- -----------------------------------------------------

DELIMITER $$
CREATE FUNCTION get_team_level_count(_parent_id BIGINT)
RETURNS INT
BEGIN
	
	DECLARE _level_count INT DEFAULT 0;
    
    WITH RECURSIVE _team_levels (id, _level) AS
	(
		SELECT id, 1 _level
		FROM team_members
		WHERE parent_id = _parent_id
	  
		UNION ALL

		SELECT c.id, cp._level + 1
		FROM _team_levels AS cp 
		JOIN team_members AS c
			ON cp.id = c.parent_id
	)
    
    SELECT max(_level) FROM _team_levels
	INTO _level_count;
    
    IF _level_count IS NULL THEN
		SET _level_count = 0;
	END IF;
	
	RETURN _level_count;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure level_members
-- -----------------------------------------------------

DELIMITER $$
CREATE PROCEDURE level_members(IN _parent_id INT)
BEGIN
    
     WITH RECURSIVE _team_levels (id, _level) AS
	(
		SELECT id, 1 _level
		FROM team_members
		WHERE parent_id = _parent_id
	  
		UNION ALL

		SELECT c.id, cp._level + 1
		FROM _team_levels AS cp 
		JOIN team_members AS c
			ON cp.id = c.parent_id
	)

	SELECT _level, count(id) member_count FROM _team_levels
	GROUP BY _level
    ORDER BY _level ASC;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `v_team_members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `v_team_members`;
CREATE  OR REPLACE VIEW `v_team_members` AS
SELECT t.id, t.member_id, t.user_id,  t.parent_id,  t.created_at AS member_since, t.citizen_id, c.citizen_id AS citizen_uuid, c.id_card, c.first_name, c.last_name,
	(
    SELECT COUNT(id)schedules
    FROM `team_members` AS t1
    WHERE t1.`parent_id` = t.id
  ) AS member_count,
  get_team_level_count(t.id) AS level_count
FROM team_members t
INNER JOIN citizens c
	ON c.id = t.citizen_id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
